name: Verifier

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov
      # Login to github
      - name: Login
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
      # Fetch all history for all tags and branches
      - name: Fetch all history for all tags and branches
        run: |
          git fetch --prune --unshallow
      # Git test
      - name: Git test
        run: |
          git diff HEAD~1..HEAD --
      # Now create a step that makes sure that there is only one file that is being changed
      - name: Check if only one file is changed
        run: |
          if [ $(git diff --name-only HEAD~1..HEAD | wc -l) -eq 1 ]; then
            echo "Only one file has been modified"
          else
            echo "More than one file has been modified"
            echo "The number of files modified is $(git diff --name-only HEAD~1..HEAD | wc -l)"
            exit 1
          fi
      # Now make sure that the file is a .py file
      - name: Check if the file is a .py file
        run: |
          if [ $(git diff --name-only HEAD~1..HEAD | grep -c ".py") -eq 1 ]; then
            echo "Only one .py file exists!"
          else
            echo "More than one .py file exists!"
            echo "The number of .py files is $(git diff --name-only HEAD~1..HEAD | grep -c ".py")"
            exit 1
          fi
      # The files are stored like "Challenges/Topic/Task/Task.py" 
      # Now test the py file by running pytest on the file at location ".github/workflows/Challenge_verifiers/x" where x = "Topic/Task/Task.py" 
      # So if i complete "Challenges/Basic_Programs/add_two_numbers/add_two_numbers.py" then the verifier file will be at ".github/workflows/Challenge_verifiers/Basic_Programs/add_two_numbers/add_two_numbers.py"
      - name: Run pytest
        run: |
          ls -la
          echo "Running pytest on .github/workflows/$(git diff --name-only HEAD~1..HEAD)"
          pytest .github/workflows/$(git diff --name-only HEAD~1..HEAD)