name: Verifier

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov

      # Now create a step that makes sure that there is only one file that is being changed
      - name: Check if only one file is changed
        run: |
          if [ $(git diff --name-only HEAD~1..HEAD | wc -l) -eq 1 ]; then
            echo "Only one file has been modified"
          else
            echo "More than one file has been modified"
            exit 1
          fi